### ISSUE TITLE
Not working on pytorch 0.4.1

### ISSUE THREAD

**Issue by crewleader** [1zb/deformable-convolution-pytorch#17]
It is not working on pytorch 0.4.1.

**Comment by lxtGH** [comment]
Hi, Have you successfully run this code?

**Comment by ghost** [comment]
@1zb @lxtGH same problem, not work under  PyTorch 0.4.1

```
/media/zlq/Experiments/YOLOv3_Pytorch/nets/src/deform_conv_cuda.c:12:20: error: invalid use of incomplete type ‘THTensor {aka struct THTensor}’
   THArgCheck(weight->nDimension == 4, 5,

```

**Comment by wuzy2115** [comment]
It could work on Pytorch 0.3.1
